apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-proj
  labels:
    app: weather

spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather

  template:
    metadata:
      labels:
        app: weather

    spec:
      containers:
      - name: weather-app-server
        image: doronamsalem/k8s_proj:weather_website_32
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: k8s-proj-svc
spec:
  selector:
    app: weather
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
